sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - hexo
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master #部署到master分支
  on:
    branch: hexo
  local-dir: public
